### ISSUE TITLE
Смена лицензии на Creative Commons

### ISSUE THREAD

**Issue by averyanalex** [AShepelevv/astro.notebook#228]
В данный момент лицензия запрещает распространение производных работ без согласования с автором. В случае, если авторы пропадут/им будет лень/ещё 100 причин, не будет возможности легально дополнять и исправлять астрадь. Я хочу предложить изменить лицензию на что-то копилефтное, запрещающее коммерческое использование. Например, [CC BY-NC](https://en.m.wikipedia.org/wiki/Creative_Commons_NonCommercial_license).

**Comment by AShepelevv** [comment]
Добрый день, @averyanalex!

Спасибо за предложение. Смею вас уверить, в ближайшем будущем ничего из этого не планируется:
> авторы пропадут/им будет лень/ещё 100 причин

При появлении мыслей в эту сторону, обязательно озаботимся вопросом изменения лицензии.

Сейчас лицензия не запрещает коммитить в данный репозиторий и делать Pull Requests в ветку master, как уже было сказано в #230. 

Спасибо!

**Comment by averyanalex** [comment]
Дело в том, что всё ещё есть пара проблем.

Во первых, уж простите, никто из погибших в авиакатастрофах не планировал этого делать. Приведу это как пример, остальные сценарии перечислять не буду.
> Спасибо за предложение. Смею вас уверить, в ближайшем будущем ничего из этого не планируется:
> При появлении мыслей в эту сторону, обязательно озаботимся вопросом изменения лицензии.

Во вторых, право коммитить есть, очевидно, не у всех. Кидать PR - да, у всех, но авторское право в лицензии записано лично за вами. Опять же, будущее может быть немного неясным.
> Сейчас лицензия не запрещает коммитить в данный репозиторий и делать Pull Requests в ветку master, как уже было сказано в #230.

Кстати говоря, все лицензии CC BY обязывают указывать имя первоначального автора при распространении оригинала или изменённой версии, если вам это важно.

Не думайте, что я уговариваю вас "отдать всем свой труд бесплатно на неконтроллируемое использование". Это зависит от ваших целей. Свободное и бесплатное образование в области астрономии, или оно же, но именно по вашей одобренной программе?

Если же вы действительно хотите запретить создание производных без вашего разрешения (но действительно ли это хорошо остальным? В конце концов, образование, тем более бесплатное - это про помощь обществу), обратите внимание на [CC BY-NC-ND](https://creativecommons.org/licenses/by-nc-nd/4.0/deed.ru). Она, как минимум, общеизвестна и проработана профессиональными юристами, и она как раз-таки запрещает и коммерческое использование, и производные без разрешения (сразу отвечу на вопрос "она же разрешает любое, а не только образовательное использование" - других ведь у таких произведений нет, в крайнем случае научпоп, но это ведь тоже образование).

Пожалуйста, не воспринимайте это как критику или что-то подобное, просто я помню, как у прошлой астради были ошибки и не было исходников, а теперь исходники как бы есть, но прав на их редактирование может не быть (сделаем вид, что авторское право реально соблюдается). Не хочется, чтобы что-то подобное стало препятствием для образования.

В любом случае, спасибо за ваш (и остальных авторов) труд, он был полезен мне и будет полезен другим вне зависимости от таких формальностей, как выбор лицензии :)

**Comment by averyanalex** [comment]
Забыл упомнять важное добавление к CC лицензии: SA (Share-Alike), т.е. производные работы обязаны распространяться под такой же лицензией. Ваша текущая лицензия, по идее, такого не ограничивает, и все, кому дано право на модификацию, могут и лицензию поменять на разрешающую что угодно. И упоминание авторов (BY расширение к CC)  у вас не прописано, поэтому те, кому дано право на изменение, могут и авторов вычеркнуть и не упоминать.
