### ISSUE TITLE
Provide a convenient way to get a written permission to edit the source code

### ISSUE THREAD

**Issue by WeetHet** [AShepelevv/astro.notebook#230]
According to the license
> Modification <...> is strictly prohibited without prior written permission from the copyright holder.

But there's no convenient way to acquire such a permission. I propose a creation of a list of people allowed to edit the repo as a markdown file inside the repository, something like `EDITORS.md`. #228 could also address this issue, but in the current state, this is the best solution I can come up with. By filing this issue I also request the permission to modify the source code from the authors

**Comment by AShepelevv** [comment]
> creating a pull request requires forking and modifying the forked copy

You do not really need to fork repository to create a Pull Request. It is enough to create a branch, commit to the brunch, push it and create a Pull Request at this original repository.

**Comment by averyanalex** [comment]
> > creating a pull request requires forking and modifying the forked copy
> 
> You do not really need to fork repository to create a Pull Request. It is enough to create a branch, commit to the brunch, push it and create a Pull Request inside this original repository.

Creating a branch is a creation of derivative version, and publishing it to github is a distribution. Also, only developers of original repo can push to it, other people must create fork.

**Comment by WeetHet** [comment]
> > creating a pull request requires forking and modifying the forked copy
> 
> You do not really need to fork repository to create a Pull Request. It is enough to create a branch, commit to the brunch, push it and create a Pull Request inside this original repository.

I don't have write access to the repo, so I can't create a branch in the original repo

**Comment by AShepelevv** [comment]
I am really sorry about my mistake. I did not know that non-collaborators must have the push permission to create a branch in a public repository. Therefore, the license has been changed according to #228. Thank you all for your help!

If you want to contribute frequently to the repo, we can discuss giving you a collaborator role.
